name: Scrape mlb data

on: 
  push: 
  workflow_dispatch:
  schedule:
    - cron: '17 * * * *'

jobs:
    scheduled:
      runs-on: ubuntu-latest
      steps:
          - name: Check out this repo
            uses: actions/checkout@v2
          - name: Fetch latest data
            run: |-
              curl https://projects.fivethirtyeight.com/mlb-api/mlb_elo.csv > data/mlb_elo.csv
          - name: Commit and push data files
            run: |-
              git config user.name "Automated"
              git config user.email "actions@users.noreply.github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Latest data: ${timestamp}" || exit 0
              git push
